### ISSUE TITLE
Add random restarts to check how it recovers

### ISSUE THREAD

**Issue by krasi-georgiev** [prometheus/test-infra#154]
To catch bugs that happen only after a restart. Sometimes after running Prometheus for long time followed by a restart doesn't recover.

Like https://github.com/prometheus/prometheus/issues/4603

**Comment by krasi-georgiev** [comment]
Oh maybe that one was on upgrade.

**Comment by geekodour** [comment]
Will this not affect the running benchmarks run by the querier and scaler? or it's about affecting the benchmarks? I mean, In case if the prometheus server does not recover the benchmarks will not be what would be expected.

**Comment by krasi-georgiev** [comment]
if both running Prometheus are restarted at the same time it will not affect the bench tests.

The idea os that killing Prometheus even when it is in the middle of compaction or some other operation shouldn't prevent the next normal startup. 

This happened on few occasions.

The graphs would be reset with these restarts, but that is not important as we just compare both versions so if these should look  similar when both are restarted at the same time.

**Comment by geekodour** [comment]
oh yes, I see. So, for this I think deleting the pods for Prometheus Master and Prometheus PR should work ?

**Comment by geekodour** [comment]
I've not tested this yet but this is a sleep timer using `$RANDOM` . I've explored other ways like k8s cronjobs and liveness but I think this should do.

modifying `components/prombench/manifests/benchmark/3_prometheus-test.yaml`

```yaml
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus:{{ .RELEASE }}
        imagePullPolicy: Always
        command: [ "/bin/sh", "-c" ]
        args:
        - runwithrestarts(){
            /bin/prometheus \
            --web.external-url=http://prombench.prometheus.io/{{ .PR_NUMBER }}/prometheus-release \
            --storage.tsdb.path=/prometheus \
            --web.console.libraries=/etc/prometheus/console_libraries \
            --web.console.templates=/etc/prometheus/consoles \
            --config.file=/etc/prometheus/prometheus.yml \
            --log.level=debug &;
            prompid=$!;
            sleep $[ ($RANDOM % 100) + 45 ]m;
            kill -9 $prompid;
            runwithrestarts;
          }
          runwithrestarts;
        #args: [
        #  "--web.external-url=http://prombench.prometheus.io/{{ .PR_NUMBER }}/prometheus-release",
        #  "--storage.tsdb.path=/prometheus",
        #  "--web.console.libraries=/etc/prometheus/console_libraries",
        #  "--web.console.templates=/etc/prometheus/consoles",
        #  "--config.file=/etc/prometheus/prometheus.yml",
        #  "--log.level=debug"
        #]
```

I'll test this soon.
